# fly.toml app configuration file generated for webatar on 2024-10-05T20:22:12+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'webatar'
primary_region = 'iad'

[build]
  [build.args]
    GO_VERSION = '1.23'

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
